services:
  - type: web
    name: spotify-downloader
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    preDeployCommand: |
      apt-get update -y
      apt-get install -y ffmpeg python3-pip
      pip3 install yt-dlp
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://spotify-downloader.onrender.com
      - key: SPOTIFY_CLIENT_ID
        value: b0ad6d6cea8b4727a4d391ccc8f5c110
      - key: SPOTIFY_CLIENT_SECRET
        value: 4ed3757cf3914fc5a2ddc4e93c81d781
    healthCheckPath: /
    autoDeploy: true
