services:
  - type: web
    name: spotify-downloader
    env: node
    buildCommand: npm run render-build
    startCommand: npm start
    preDeployCommand: |
      apt-get update -y
      apt-get install -y ffmpeg python3-pip
      pip3 install yt-dlp
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://spotify-downloader.onrender.com
    healthCheckPath: /
    autoDeploy: true
